Adding vehiculo CRUD
giraldeveloper/ph-back pull request #5
Opened 2023-01-27 06:20 UTC by KevinCastroP

@andresfgiraldo  please make the review of this commit and let me know if everything is ok.

2023-01-27 15:07 UTC, andresfgiraldo requested changes

2023-01-27 15:07 UTC, andresfgiraldo commented on src/vehiculo/entities/vehiculo.entity.ts
> +export class Vehiculo extends BaseEntity{
extender de CommonBaseEntityAudit así evitamos tener las columnas de auditoria (usuario y fechas) en cada entity.
EJ: https://github.com/giraldeveloper/ph-back/blob/c4ff74cf6d55c978578070d78829d48e7dfbf7c9/src/inmueble/entities/inmueble.entity.ts#L9

2023-01-27 15:07 UTC, andresfgiraldo commented on src/vehiculo/entities/vehiculo.entity.ts
> +    @Column({ length: 45, name: "usuario_sistema", nullable: true })
remover al extender de CommonBaseEntityAudit

2023-01-27 15:07 UTC, andresfgiraldo commented on src/vehiculo/entities/vehiculo.entity.ts
> +    fechaCreacion: Date; // Creation date
remover al extender de CommonBaseEntityAudit

2023-01-27 15:07 UTC, andresfgiraldo commented on src/vehiculo/entities/vehiculo.entity.ts
> +    fechaModificacion: Date; // Last updated date
remover al extender de CommonBaseEntityAudit

2023-01-27 15:07 UTC, andresfgiraldo commented on src/vehiculo/vehiculo.service.ts
> +    const eTipoVehiculo: ETipoVehiculo = ETipoVehiculo[this.getKeyByValue(ETipoVehiculo, tipoVehiculo)];
getKeyByValue ahora es una funcion global. usar desde 
https://github.com/giraldeveloper/ph-back/blob/c4ff74cf6d55c978578070d78829d48e7dfbf7c9/src/common/enums/utils.ts#L1

2023-01-27 15:07 UTC, andresfgiraldo commented on src/vehiculo/vehiculo.service.ts
> +  private getKeyByValue<T>(e: T, value: string): string {
remover y usar la funcion global

2023-01-27 15:07 UTC, andresfgiraldo commented on src/vehiculo/entities/vehiculo.entity.ts
> +export enum ETipoVehiculo {
mover a directorio enums del common:
EJ. https://github.com/giraldeveloper/ph-back/blob/c4ff74cf6d55c978578070d78829d48e7dfbf7c9/src/common/enums/ETipoIdentificacion.ts#L1

2023-01-28 01:01 UTC, KevinCastroP commented on src/vehiculo/entities/vehiculo.entity.ts
> +export enum ETipoVehiculo {
done!

2023-01-28 01:04 UTC, KevinCastroP commented on src/vehiculo/vehiculo.service.ts
> +  private getKeyByValue<T>(e: T, value: string): string {
done!

2023-01-28 01:08 UTC, KevinCastroP commented on src/vehiculo/vehiculo.service.ts
> +    const eTipoVehiculo: ETipoVehiculo = ETipoVehiculo[this.getKeyByValue(ETipoVehiculo, tipoVehiculo)];
done!

2023-01-28 01:10 UTC, KevinCastroP commented on src/vehiculo/entities/vehiculo.entity.ts
> +    fechaModificacion: Date; // Last updated date
done!

2023-01-28 01:11 UTC, KevinCastroP commented on src/vehiculo/entities/vehiculo.entity.ts
> +    fechaCreacion: Date; // Creation date
done!

2023-01-28 01:11 UTC, KevinCastroP commented on src/vehiculo/entities/vehiculo.entity.ts
> +    @Column({ length: 45, name: "usuario_sistema", nullable: true })
done!

2023-01-28 01:11 UTC, KevinCastroP commented on src/vehiculo/entities/vehiculo.entity.ts
> +export class Vehiculo extends BaseEntity{
done!

2023-01-28 04:50 UTC, andresfgiraldo approved these changes

2023-01-28 04:50 UTC, merged